### ISSUE TITLE
Motorola One Action kernel source

### ISSUE THREAD

**Issue by meganukebmp** [MotorolaMobilityLLC/kernel-slsi#3]
Hello, I'm requesting the kernel sources of Motorola One Action `troika`/`troika_sprout` Android 9.X, tag PSBS29.39-23-6

**Comment by chenyt9** [comment]
@meganukebmp ，
https://github.com/MotorolaMobilityLLC/kernel-slsi/releases/tag/MMI-PSB29.39-49-7
Does this version meet your needs? If not, please let me know and I will arrange the release of the version（PSBS29.39-23-6）.Thanks a lot.

**Comment by meganukebmp** [comment]
Yes, thank you, excuse me as I had not noticed it at first.
