### ISSUE TITLE
Moto One Action Kernel Source for Android 10 QSB30

### ISSUE THREAD

**Issue by Oves786** [MotorolaMobilityLLC/kernel-slsi#4]
Moto One Action Kernel Source for Android 10 tag -TROIKA_QSB30.62-17

**Comment by chenyt9** [comment]
Hi,@Oves786 ，
I have started to prepare for the release of this version. Due to some processes, it will take about two weeks. Please be patient, thank you!

**Comment by chenyt9** [comment]
@Oves786 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-slsi/releases/tag/MMI-QSB30.62-17
Thanks.
