### ISSUE TITLE
[Request] Kernel sources for Motorola One Vision (kane) with tag QSAS30.62-24-3

### ISSUE THREAD

**Issue by arch-dev** [MotorolaMobilityLLC/kernel-slsi#5]
Good morning,
I've opened this issue to request Android Q kernel sources update for Motorola One Vision (kane) with tag QSAS30.62-24-3. Thank you.

Regards Sebastiano Galeazzo

**Comment by chenyt9** [comment]
Hi，@arch-dev ，
I have started to prepare for the release of this version. Due to some processes, it will take about two weeks. Please be patient, thank you!

**Comment by arch-dev** [comment]
Thank you @chenyt9

**Comment by chenyt9** [comment]
Hi，@arch-dev 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-slsi/releases/tag/MMI-QSAS30.62-24-3
Thanks.

**Comment by arch-dev** [comment]
Thank you very much.
