### ISSUE TITLE
Build instructions for Kane/Troika

### ISSUE THREAD

**Issue by deadman96385** [MotorolaMobilityLLC/kernel-slsi#6]
Hello @chenyt9, could instructions on the proper procedure to compile the QSAS or QSB kernel releases be posted here or in the README repo. It would be very helpful.

**Comment by chenyt9** [comment]
@deadman96385,
Please refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QSB30.62-17.txt
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QSAS30.62-24-3.txt
Thanks.
