### ISSUE TITLE
exynos source request

### ISSUE THREAD

**Issue by Stricted** [MotorolaMobilityLLC/kernel-slsi#7]
this is probably the wrong place for this but  ¯\_(ツ)_/¯

can you please release the source code of `libwifi-hal-slsi` ?
it is placed under `hardware/samsung_slsi/scsc_wifibt/wifi_hal` and `hardware/samsung_slsi/scsc_wifibt/wpa_supplicant_lib`

also the following things would be nice to have the actual source for
`hardware/samsung_slsi/libbt` (which is the source for libbt-vendor.so)
and `hardware/samsung_slsi/boot_control` (which is the bootctrl source, this one is not important since i reverse engineered it already)

also the source for `libfmservicejni.so` would be a nice to have (needed to get fmradio working on aosp roms)

**Comment by awheeler-mmi** [comment]
Hey @Stricted , 

We receive this wifi driver and supplicant from SLSI, as part of their closed-source release.  I don't think we have a license to open-source it.  I also can't find where SLSI is open-sourcing it, or I would just give you our commit sha1.  I'll ask our wifi team to follow-up with their SLSI counterparts.

**Comment by awheeler-mmi** [comment]
The FM radio jni is mostly Motorola/Lenovo code, but it includes at least a proprietary header from SLSI.  I can also let the team that owns this project that customers would like to open-source the jni.

More generally, I'll start tracking a list of projects that customers would like open-sourced, including the hardware/samsung_slsi projects you mentioned above, and talk about it with our software leads.

**Comment by Stricted** [comment]
@awheeler-mmi any news on this? i would really like to have `wifi_hal` and `wpa_supplicant_lib` sources

i have reverse engineered everything else (FM, bt and boot_control), only wifi is missing in my custom rom

i already started reverse engineering the wifi hal but its tedious and alot of work

i would really love to see source for these basic things

**Comment by chenyt9** [comment]
@Stricted ,
Code released:
https://github.com/MotorolaMobilityLLC/hardware-samsung_slsi-scsc_wifibt-wifi_hal/releases/tag/MMI-QSBS30.62-17-8
Thanks.
